function regression_matrix_num = min_regressor(q, dq, ddq)
    load('F:\Master\毕设文件\code\Dynamic_Parameter_Identification_for_Rokae_xMate\excitation\data\regression_matrix.mat', 'regression_matrix');

    th1 = q(1); QP1 = dq(1); QDP1 = ddq(1);
    th2 = q(2); QP2 = dq(2); QDP2 = ddq(2);
    th3 = q(3); QP3 = dq(3); QDP3 = ddq(3);
    th4 = q(4); QP4 = dq(4); QDP4 = ddq(4);
    th5 = q(5); QP5 = dq(5); QDP5 = ddq(5);
    th6 = q(6); QP6 = dq(6); QDP6 = ddq(6);
    th7 = q(7); QP7 = dq(7); QDP7 = ddq(7);

    regression_matrix_num = eval(subs(regression_matrix, ...
        {'g', 'th1', 'QP1', 'QDP1', ...
              'th2', 'QP2', 'QDP2', ...
              'th3', 'QP3', 'QDP3', ...
              'th4', 'QP4', 'QDP4', ...
              'th5', 'QP5', 'QDP5', ...
              'th6', 'QP6', 'QDP6', ...
              'th7', 'QP7', 'QDP7'}, ...
        { g ,  th1 ,  QP1 ,  QDP1 , ...
               th2 ,  QP2 ,  QDP2 , ...
               th3 ,  QP3 ,  QDP3 , ...
               th4 ,  QP4 ,  QDP4 , ...
               th5 ,  QP5 ,  QDP5 , ...
               th6 ,  QP6 ,  QDP6 , ...
               th7 ,  QP7 ,  QDP7 }));
end